name: Terraform Apply

on:
  workflow_run:
    workflows: ['Terraform Plan']  # Triggers after 'Terraform Plan' workflow completes
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
           aws-region: eu-west-2  # Matches the default region in variables.tf but isn't terraform so either set as a GitHub secret or specify the actual region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var="region=eu-west-2"
