name: Drift Detection

on:
  schedule:
    - cron: '*/45 * * * *'  # Runs every 45 minutes

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    environment: production
    permissions: 
      id-token: write  # Required for OIDC auth
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: eu-west-2  # Matches the default region in variables.tf but isn't terraform so either set as a GitHub secret or specify the actual region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check if State File Exists
        id: check_state
        run: |
          if [ -f "./terraform/terraform.tfstate" ]; then
            echo "State file found."
            echo "state_exists=true" >> $GITHUB_ENV
          else
            echo "No state file found. Skipping drift detection."
            echo "state_exists=false" >> $GITHUB_ENV
          fi

      - name: Initialize Terraform
        if: env.state_exists == 'true'
        run: terraform init -no-color -input=false -lock=false
        working-directory: ./terraform

      - name: Run Terraform Plan for Drift Detection
        if: env.state_exists == 'true'
        run: terraform plan -no-color -lock=false -detailed-exitcode -compact-warnings -out drift.tfplan
        continue-on-error: true
        working-directory: ./terraform