name: 'Terraform Format Check'

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  terraform_fmt:
    name: 'Terraform Fmt Check'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
