name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  id-token: write

jobs:
  terraform:
    name: 'Terraform Fmt Check and Plan'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: fmt_check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Format and Commit Changes
        if: steps.fmt_check.outcome == 'failure'
        run: |
          terraform fmt -recursive
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "[Terraform Fmt] Automated Terraform format correction"
          git push

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: eu-west-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -var="region=eu-west-2" -out=plan.out